//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejar_new.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public int reservation_id { get; set; }
        public System.DateTime period_start { get; set; }
        public System.DateTime period_end { get; set; }
        public int user_id { get; set; }
        public int apartment_id { get; set; }
        public int period { get; set; }
    
        public virtual Apartment Apartment { get; set; }
    }
}
